### ISSUE TITLE
Trouble shotting during reproducing experiments on the DREAMER dataset

### ISSUE THREAD

**Issue by tczhangzhi** [ELEMKEP/bsc_lcs#2]
Hi, there! Thanks for your great work!
I met some trouble during reading your paper and reproducing experiments on the DREAMER dataset.

https://github.com/ELEMKEP/bsc_lcs/blob/9972660a947d7a7244cd9eeab202857c87dd3112/data/lmdb_generate.py#L41

Could you please explain the process of generating `Process.mat` based on `DREAMER.mat`? It looks like you have concatenated the data of each TRAIL together. Have you performed any other operations? I would appreciate it if you could provide the code.

**Comment by ELEMKEP** [comment]
Thanks for your attention!

Due to the inconvenient interface of reading .mat file in python, the pre-processing for DREAMER.mat file was conducted on the MATLAB. The pre-processing in .mat file has nothing special but picking the necessary data from DREAMER.mat file, rearranging them, and cut the dataset by the first 60-second. I forgot to include the .m file in the repo, but it can be implemented in python, so I will implement it and update them.

It'll takes some time, and I'll send you e-mail with the .m file.

**Comment by tczhangzhi** [comment]
Thanks for your fast reply, it works well. And I believe most of the experimental results are stable after large amounts of epochs of training. Good job!
